# Дженерик Promise

Для типизации асинхронной функции используется дженерик `Promise<>`. Его надо закрыть типом, который мы хотим вернуть из функции. При этом, если в результате ошибки мы делаем reject с объектом Error, то отражать это в типе не обязательно, т.е. достаточно закрыть `Promise<>` типом успешного результата:

```typescript
function init(config): Promise<IDatabase> {  // <-- Достаточно указать тип "успеха".
  const database = SomeAPI.openDb(config);
  if (database) {
    resolve(database)
  } else {
    reject(new Error("Не удалось открыть БД."));
  }
}
```

# Выброс исключения

Если выбросить исключение в функции, которая возвращает тип Promise<>, то это равнозначно тому, что вернуть из нее отклоненный промис:

```typescript
function equal(a: number, b: number): Promise<string> {
  if (a !== b) {
    throw new Error(`Ошибка: ${a} !== ${b}`);  // <-- Аналогично reject'у промиса.
  }
  return new Promise(resolve => {
    resolve(`Успех: аргументы ${a} и ${b} равны.`);
  });
}

async function test(a: number, b: number) {
  try {
    const result = await equal(a, b);
    console.log(result);
  } catch (error) {
    console.log(error);
  }
}

test(7, 7);
test(7, 12);
```

