# "Другие функции" находятся в других модулях

Есть вот такая функция, которая вызывает функции из других модулей:

```typescript
import { defaultApiUrlBuilder as builder } from "@api/endpoints/endpoints";
import { fetchData } from "@api/fetchData/fetchData";
import { Task } from '@src/types/model/Task';

export async function fetchTaskById(taskId: number) {
  const url = builder.getTaskByIdUrlBuilder(taskId);
  const task = await fetchData<Task>(url);
  return task;
}
```

Чтобы протестировать fetchTaskById надо для нее замокировать builder.getTaskByIdUrlBuilder и fetchData:

```typescript
import { describe, it, expect, vi, beforeAll } from 'vitest';
import { fetchTaskById } from '../fetchTaskById';
// <-- Импортируем зависимости тестируемой функции.
import { defaultApiUrlBuilder as builder } from '@api/endpoints/endpoints';  // <-- 1
import { fetchData } from '@api/fetchData/fetchData';  // <-- 2


vi.mock('@api/endpoints/endpoints');  // <-- Указываем модуль, который будем мокать.
vi.mock('@api/fetchData/fetchData');


describe('fetchTaskById', () => {
  let taskId, url, task;

  beforeAll(() => {
    ({ taskId, url, task } = prepareMockData());
    vi.mocked(builder.getTaskByIdUrlBuilder).mockReturnValue(url);  // <-- Мокаем результат функции.
  });


  it('Возвращает задачу по id.', async () => {
    vi.mocked(fetchData).mockResolvedValue(task);  // <-- Мокаем результат функции.

    // <-- Пациент работает как обычно, не подозревая, что вызывает подмоченные функции.
    const result = await fetchTaskById(taskId);

    expect(builder.getTaskByIdUrlBuilder).toHaveBeenCalledWith(taskId);
    expect(fetchData).toHaveBeenCalledWith(url);
    expect(result).toEqual(task);
  });

  
  it('Перевыбрасывает исключение в случае ошибки в fetchData.', async () => {
    vi.mocked(fetchData).mockRejectedValue(new Error('Foobar error'));

    const error = await fetchTaskById(taskId).catch(err => err);
    
    expect(error).toBeInstanceOf(Error);
    expect(error).toMatchObject({ message: 'Foobar error' });
  });
});


function prepareMockData() {
  return {
    taskId: 777,
    url: 'https://localhost:7077/tasks/nomatter/777',
    task: {
      id: 1,
      title: "Закончить проект",
      completed: false,
      description: "Доделать финальные правки и отправить на проверку",
      createdAt: "2023-05-15T10:30:00",
      priority: "high",
      tags: ["work", "important"]
    }
  }
}
```

Как это работает:

* Через vi.mock мы указываем, что этот модуль мы хотим мокать. Т.о. пациент будет использовать не реальный модуль, а мок.
  * Эта штука заменяет все экспорты из указанного модуля на моки.
* vi.mocked(builder.getTaskByIdUrlBuilder).mockReturnValue(url) - получаем замоканную функцию из модуля и указываем какое значение она должна возвращать, когда пациент попробует вызвать ее вызвать.
* Пациент вызывает функции как обычно, но вместо них работают моки. Т.о. мы заранее знаем, что получит пациент и можем тестировать его реакцию.





# "Другие функции" находятся в этом же модуле

TODO