# Ошибки в отложенном коде

try-catch работает синхронно. Это значит, что он не поймает ошибку в коде, который выполнится в будущем. Например:

```java
try {
  setTimeout(() => noSuchVariable, 1000);
} catch (err) {
  console.log("Ошибка обработана");
}
```

В таких случаях надо ловить ошибку в самом отложенном коде.