# Самописные проверки

## Пример

```javascript
const schema = z.object({
  password: z.string()
    .refine(val => val !== "", {  // <-- a, errors.password
      message: "Введите пароль.",
    })
    .refine(val => val.length > 5, {  // <-- b, errors.password
      message: "Пароль должен быть длиннее 5 символов."
    }),
  confirmPassword: z.string()
    .refine(val => val !== "", {  // <-- c, errors.confirmPassword
      message: "Введите пароль повторно в это поле.",
    }),
  user: z.object({
    firstname: z.string(),  // <-- errors.user.firstname
    lastname: z.string(),  // <-- errors.user.lastname
    age: z.number({ message: "Укажите возраст."})  // <-- d, errors.user.age
  })
    .refine(val => val.firstname !== "" && val.lastname !== "", {  // <-- e, errors.user
      message: "Обязательно заполните имя и фамилию."
    })
    .refine(val => val.age > 18, {  // <-- f, errors.user.age
      message: "Регистрация доступна только с 18 лет.",
      path: ["age"]
    })
})
  .refine(val => val.password === val.confirmPassword, {  // <-- g, errors[""]
    message: "Пароли не совпадают.",
    // path: ["form"]  // <-- Тогда ошибка попадет в errors["form"]
  });
```

## Как делается проверка?

Методами `refine` и `superRefine`. Они принимают функцию -> bool. Вернула true - валидация пройдена, false - не пройдена.

```javascript
foobar.number().refine(val => val % 2 === 0);
```

## Как задать сообщение ошибки?

Второй параметр - объект, у которого есть поле message:

```javascript
foobar.number().refine(val => val % 2 === 0, {
  message: "Число должно быть четное."
});
```

Если в тексте ошибки нужно получить доступ к провеяемому значению:

```javascript
foobar.number().refine(val => val % 2 === 0, 
  (val) => ({ message: `${val} нечетное, а допускаются только четные числа.` })
);
```

## К чему можно применить?

К любому полю - хоть простому, хоть со вложенными полями.

## Как добраться до ошибок валидации?

* Если используется в паре с react-hook-form, то хук useForm возвращает `formState.errors`. 
* Ошибки складываются в свойства объекта errors. Свойства образуются исходя из структуры схемы: errors.password, errors.confirmPassword, errors.user.age и т.д.
* Свойство можно сформировать самостоятельно через path. Формула `автоматический путь + path`. Если внутри path несколько значений, они соединяются во вложенные свойства. Например `path: ["age", "year"]` даст errors.user.age.year.
* Если refine вызван на корневом объекте схемы, ошибка попадает в свойство errors[""]. Можно для большей наглядности задать path: ["form"], тогда будет errors["form"].

Рекомендации:

* Лучше пользоваться путями, которые реально есть в схеме. Тогда react-hook-form сможет сопоставить ошибки с реальными элементам формы и например автоматически сделать фокус на поле с ошибкой.



















## Параметр RefineParams

??? Надо ли

## Кастомный текст ошибки

```javascript
foobar.number().refine(val => val % 2 === 0, {
  message: "Число должно быть четное."
});
```

## Привязка ошибки к полю схемы

Если refine применяется к простому полю, тогда ошибка к этому полю и привязывается:

```javascript
foobar.number().refine(val => val % 2 === 0, {  // <-- Привяжется к полю foobar
  message: "Число должно быть четное."
});
```







Второй параметр - это объект RefineParams:

```javascript
{
  message?: string;  // <-- Кастомное сообщение для ошибки.
  path?: (string | number)[];  // <-- К какому полю привязать ошибку.
  params?: object;  // <-- ???
};
```

`path` актуально только для случаев, когда refine применяется к полю-объекту. Тогда можно указать, к какому именно полю относится ошибка:

```javascript
const schema = z.object({
  password: z.string()
    .refine(val => val !== "", {  // <-- Тут path не актуален, refine на простом поле.
      message: "Вы не указали пароль.",
    }),
  confirmPassword: z.string(),
  user: z.object({
    firstname: z.string(),
    lastname: z.string(),
    age: z.number()
  })
}).refine(val => val.user.lastname !== "", {
  message: "Обязательно введите фамилию.",
  path: ["user", "lastname"]  // <-- path указывает путь к конкретному полю схемы.
});
```





* Методы

  * `refine(checkFn, custom)` - TODO описание.

  * `superRefine(checkFn, custom)` - TODO описание.

  * Можно чейнить.

  * `checkFn(val => bool)` -> true - валидация пройдена, false - не пройдена.

  * `obj | fn(val => obj)`  - настройка ошибки:

    ```javascript
    {
      message: "Кастомный текст для ошибки",
      path: ["ПолеСхемы"],  // <-- Поле, к которому привязать ошибку.
      params:
    }
    ```

    

    

    

```typescript
const schema = z.object({
  foobar: z.string(). -> refine() | superRefine()
}). -> refine() | superRefine()
```



### .refine()



* Параметры refine и superRefine:
  * Первый: функция валидации `fn(val => boolean)` -> true - валидация пройдена, false - не пройдена.
    * val - это значение поля.
  * Второй:
    * Объект `RefineParams` | `fn(val => RefineParams)`
    * RefineParams:
      * `message?` - кастомное сообщение для ошибки.
      * `path["ПолеСхемы"]?` актуально только когда refine применяется к объекту. Можно указать, к какому именно полю привязать ошибку.
      * `params` - ???



```typescript
const schema = z.object({
  password: z.string()
    .refine(val => val !== "", {
      message: "Вы не указали пароль.",
    }),
  confirmPassword: z.string(),
  user: z.object({
    firstname: z.string(),
    lastname: z.string(),
    age: z.number()
  })
})
```







### .superRefine()

TODO



TODO: refine на отдельных полях и на схеме в целом.

```typescript
const schema = z.object({
  fromAccountId: z.string(),
  toAccountId: z.string(),
  amount: z.number()
    .positive("Сумма перевода должна быть больше нуля.")
}).refine(
    (data) => data.toAccountId !== data.fromAccountId,
    {
      message: "Счета не должны совпадать",
      path: ["fromAccountId"]
    }
);
```







# TODO

* Проверка пароля срабатывает сразу как только начинаешь вводить. Либо если сначала вводишь, потом пытаешься отправить, получается ошибка и после этого когда правишь, сразу проверяет, а не при повторной отправке.
* Куда уходят дефолтные ошибки, которые дают .number()-like проверки?